<?php
/**
 * AdresseComplementaire
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Sirene\Client\Model;

use \ArrayAccess;
use \Sirene\Client\ObjectSerializer;

/**
 * AdresseComplementaire Class Doc Comment
 *
 * @category Class
 * @description Ensemble des variables d&#x27;adresse complémentaire d&#x27;un établissement
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdresseComplementaire implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AdresseComplementaire';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'complement_adresse2_etablissement' => '',
        'numero_voie2_etablissement' => '',
        'indice_repetition2_etablissement' => '',
        'type_voie2_etablissement' => '',
        'libelle_voie2_etablissement' => '',
        'code_postal2_etablissement' => '',
        'libelle_commune2_etablissement' => '',
        'libelle_commune_etranger2_etablissement' => '',
        'distribution_speciale2_etablissement' => '',
        'code_commune2_etablissement' => '',
        'code_cedex2_etablissement' => '',
        'libelle_cedex2_etablissement' => '',
        'code_pays_etranger2_etablissement' => '',
        'libelle_pays_etranger2_etablissement' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'complement_adresse2_etablissement' => null,
        'numero_voie2_etablissement' => null,
        'indice_repetition2_etablissement' => null,
        'type_voie2_etablissement' => null,
        'libelle_voie2_etablissement' => null,
        'code_postal2_etablissement' => null,
        'libelle_commune2_etablissement' => null,
        'libelle_commune_etranger2_etablissement' => null,
        'distribution_speciale2_etablissement' => null,
        'code_commune2_etablissement' => null,
        'code_cedex2_etablissement' => null,
        'libelle_cedex2_etablissement' => null,
        'code_pays_etranger2_etablissement' => null,
        'libelle_pays_etranger2_etablissement' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'complement_adresse2_etablissement' => 'complementAdresse2Etablissement',
        'numero_voie2_etablissement' => 'numeroVoie2Etablissement',
        'indice_repetition2_etablissement' => 'indiceRepetition2Etablissement',
        'type_voie2_etablissement' => 'typeVoie2Etablissement',
        'libelle_voie2_etablissement' => 'libelleVoie2Etablissement',
        'code_postal2_etablissement' => 'codePostal2Etablissement',
        'libelle_commune2_etablissement' => 'libelleCommune2Etablissement',
        'libelle_commune_etranger2_etablissement' => 'libelleCommuneEtranger2Etablissement',
        'distribution_speciale2_etablissement' => 'distributionSpeciale2Etablissement',
        'code_commune2_etablissement' => 'codeCommune2Etablissement',
        'code_cedex2_etablissement' => 'codeCedex2Etablissement',
        'libelle_cedex2_etablissement' => 'libelleCedex2Etablissement',
        'code_pays_etranger2_etablissement' => 'codePaysEtranger2Etablissement',
        'libelle_pays_etranger2_etablissement' => 'libellePaysEtranger2Etablissement'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'complement_adresse2_etablissement' => 'setComplementAdresse2Etablissement',
        'numero_voie2_etablissement' => 'setNumeroVoie2Etablissement',
        'indice_repetition2_etablissement' => 'setIndiceRepetition2Etablissement',
        'type_voie2_etablissement' => 'setTypeVoie2Etablissement',
        'libelle_voie2_etablissement' => 'setLibelleVoie2Etablissement',
        'code_postal2_etablissement' => 'setCodePostal2Etablissement',
        'libelle_commune2_etablissement' => 'setLibelleCommune2Etablissement',
        'libelle_commune_etranger2_etablissement' => 'setLibelleCommuneEtranger2Etablissement',
        'distribution_speciale2_etablissement' => 'setDistributionSpeciale2Etablissement',
        'code_commune2_etablissement' => 'setCodeCommune2Etablissement',
        'code_cedex2_etablissement' => 'setCodeCedex2Etablissement',
        'libelle_cedex2_etablissement' => 'setLibelleCedex2Etablissement',
        'code_pays_etranger2_etablissement' => 'setCodePaysEtranger2Etablissement',
        'libelle_pays_etranger2_etablissement' => 'setLibellePaysEtranger2Etablissement'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'complement_adresse2_etablissement' => 'getComplementAdresse2Etablissement',
        'numero_voie2_etablissement' => 'getNumeroVoie2Etablissement',
        'indice_repetition2_etablissement' => 'getIndiceRepetition2Etablissement',
        'type_voie2_etablissement' => 'getTypeVoie2Etablissement',
        'libelle_voie2_etablissement' => 'getLibelleVoie2Etablissement',
        'code_postal2_etablissement' => 'getCodePostal2Etablissement',
        'libelle_commune2_etablissement' => 'getLibelleCommune2Etablissement',
        'libelle_commune_etranger2_etablissement' => 'getLibelleCommuneEtranger2Etablissement',
        'distribution_speciale2_etablissement' => 'getDistributionSpeciale2Etablissement',
        'code_commune2_etablissement' => 'getCodeCommune2Etablissement',
        'code_cedex2_etablissement' => 'getCodeCedex2Etablissement',
        'libelle_cedex2_etablissement' => 'getLibelleCedex2Etablissement',
        'code_pays_etranger2_etablissement' => 'getCodePaysEtranger2Etablissement',
        'libelle_pays_etranger2_etablissement' => 'getLibellePaysEtranger2Etablissement'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['complement_adresse2_etablissement'] = isset($data['complement_adresse2_etablissement']) ? $data['complement_adresse2_etablissement'] : null;
        $this->container['numero_voie2_etablissement'] = isset($data['numero_voie2_etablissement']) ? $data['numero_voie2_etablissement'] : null;
        $this->container['indice_repetition2_etablissement'] = isset($data['indice_repetition2_etablissement']) ? $data['indice_repetition2_etablissement'] : null;
        $this->container['type_voie2_etablissement'] = isset($data['type_voie2_etablissement']) ? $data['type_voie2_etablissement'] : null;
        $this->container['libelle_voie2_etablissement'] = isset($data['libelle_voie2_etablissement']) ? $data['libelle_voie2_etablissement'] : null;
        $this->container['code_postal2_etablissement'] = isset($data['code_postal2_etablissement']) ? $data['code_postal2_etablissement'] : null;
        $this->container['libelle_commune2_etablissement'] = isset($data['libelle_commune2_etablissement']) ? $data['libelle_commune2_etablissement'] : null;
        $this->container['libelle_commune_etranger2_etablissement'] = isset($data['libelle_commune_etranger2_etablissement']) ? $data['libelle_commune_etranger2_etablissement'] : null;
        $this->container['distribution_speciale2_etablissement'] = isset($data['distribution_speciale2_etablissement']) ? $data['distribution_speciale2_etablissement'] : null;
        $this->container['code_commune2_etablissement'] = isset($data['code_commune2_etablissement']) ? $data['code_commune2_etablissement'] : null;
        $this->container['code_cedex2_etablissement'] = isset($data['code_cedex2_etablissement']) ? $data['code_cedex2_etablissement'] : null;
        $this->container['libelle_cedex2_etablissement'] = isset($data['libelle_cedex2_etablissement']) ? $data['libelle_cedex2_etablissement'] : null;
        $this->container['code_pays_etranger2_etablissement'] = isset($data['code_pays_etranger2_etablissement']) ? $data['code_pays_etranger2_etablissement'] : null;
        $this->container['libelle_pays_etranger2_etablissement'] = isset($data['libelle_pays_etranger2_etablissement']) ? $data['libelle_pays_etranger2_etablissement'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets complement_adresse2_etablissement
     *
     * @return
     */
    public function getComplementAdresse2Etablissement()
    {
        return $this->container['complement_adresse2_etablissement'];
    }

    /**
     * Sets complement_adresse2_etablissement
     *
     * @param  $complement_adresse2_etablissement Complément d'adresse de l'établissement
     *
     * @return $this
     */
    public function setComplementAdresse2Etablissement($complement_adresse2_etablissement)
    {
        $this->container['complement_adresse2_etablissement'] = $complement_adresse2_etablissement;

        return $this;
    }

    /**
     * Gets numero_voie2_etablissement
     *
     * @return
     */
    public function getNumeroVoie2Etablissement()
    {
        return $this->container['numero_voie2_etablissement'];
    }

    /**
     * Sets numero_voie2_etablissement
     *
     * @param  $numero_voie2_etablissement Numéro dans la voie
     *
     * @return $this
     */
    public function setNumeroVoie2Etablissement($numero_voie2_etablissement)
    {
        $this->container['numero_voie2_etablissement'] = $numero_voie2_etablissement;

        return $this;
    }

    /**
     * Gets indice_repetition2_etablissement
     *
     * @return
     */
    public function getIndiceRepetition2Etablissement()
    {
        return $this->container['indice_repetition2_etablissement'];
    }

    /**
     * Sets indice_repetition2_etablissement
     *
     * @param  $indice_repetition2_etablissement Indice de répétition dans la voie
     *
     * @return $this
     */
    public function setIndiceRepetition2Etablissement($indice_repetition2_etablissement)
    {
        $this->container['indice_repetition2_etablissement'] = $indice_repetition2_etablissement;

        return $this;
    }

    /**
     * Gets type_voie2_etablissement
     *
     * @return
     */
    public function getTypeVoie2Etablissement()
    {
        return $this->container['type_voie2_etablissement'];
    }

    /**
     * Sets type_voie2_etablissement
     *
     * @param  $type_voie2_etablissement Type de la voie
     *
     * @return $this
     */
    public function setTypeVoie2Etablissement($type_voie2_etablissement)
    {
        $this->container['type_voie2_etablissement'] = $type_voie2_etablissement;

        return $this;
    }

    /**
     * Gets libelle_voie2_etablissement
     *
     * @return
     */
    public function getLibelleVoie2Etablissement()
    {
        return $this->container['libelle_voie2_etablissement'];
    }

    /**
     * Sets libelle_voie2_etablissement
     *
     * @param  $libelle_voie2_etablissement Libellé de la voie
     *
     * @return $this
     */
    public function setLibelleVoie2Etablissement($libelle_voie2_etablissement)
    {
        $this->container['libelle_voie2_etablissement'] = $libelle_voie2_etablissement;

        return $this;
    }

    /**
     * Gets code_postal2_etablissement
     *
     * @return
     */
    public function getCodePostal2Etablissement()
    {
        return $this->container['code_postal2_etablissement'];
    }

    /**
     * Sets code_postal2_etablissement
     *
     * @param  $code_postal2_etablissement Code postal
     *
     * @return $this
     */
    public function setCodePostal2Etablissement($code_postal2_etablissement)
    {
        $this->container['code_postal2_etablissement'] = $code_postal2_etablissement;

        return $this;
    }

    /**
     * Gets libelle_commune2_etablissement
     *
     * @return
     */
    public function getLibelleCommune2Etablissement()
    {
        return $this->container['libelle_commune2_etablissement'];
    }

    /**
     * Sets libelle_commune2_etablissement
     *
     * @param  $libelle_commune2_etablissement Libellé de la commune pour les adresses en France
     *
     * @return $this
     */
    public function setLibelleCommune2Etablissement($libelle_commune2_etablissement)
    {
        $this->container['libelle_commune2_etablissement'] = $libelle_commune2_etablissement;

        return $this;
    }

    /**
     * Gets libelle_commune_etranger2_etablissement
     *
     * @return
     */
    public function getLibelleCommuneEtranger2Etablissement()
    {
        return $this->container['libelle_commune_etranger2_etablissement'];
    }

    /**
     * Sets libelle_commune_etranger2_etablissement
     *
     * @param  $libelle_commune_etranger2_etablissement Libellé complémentaire pour une adresse à l'étranger
     *
     * @return $this
     */
    public function setLibelleCommuneEtranger2Etablissement($libelle_commune_etranger2_etablissement)
    {
        $this->container['libelle_commune_etranger2_etablissement'] = $libelle_commune_etranger2_etablissement;

        return $this;
    }

    /**
     * Gets distribution_speciale2_etablissement
     *
     * @return
     */
    public function getDistributionSpeciale2Etablissement()
    {
        return $this->container['distribution_speciale2_etablissement'];
    }

    /**
     * Sets distribution_speciale2_etablissement
     *
     * @param  $distribution_speciale2_etablissement Distribution spéciale (BP par ex)
     *
     * @return $this
     */
    public function setDistributionSpeciale2Etablissement($distribution_speciale2_etablissement)
    {
        $this->container['distribution_speciale2_etablissement'] = $distribution_speciale2_etablissement;

        return $this;
    }

    /**
     * Gets code_commune2_etablissement
     *
     * @return
     */
    public function getCodeCommune2Etablissement()
    {
        return $this->container['code_commune2_etablissement'];
    }

    /**
     * Sets code_commune2_etablissement
     *
     * @param  $code_commune2_etablissement Code commune de localisation de l’établissement hors établissements situés à l’étranger (Le code commune est défini dans le <a href='https://www.insee.fr/fr/information/2028028'>code officiel géographique (COG)</a>)
     *
     * @return $this
     */
    public function setCodeCommune2Etablissement($code_commune2_etablissement)
    {
        $this->container['code_commune2_etablissement'] = $code_commune2_etablissement;

        return $this;
    }

    /**
     * Gets code_cedex2_etablissement
     *
     * @return
     */
    public function getCodeCedex2Etablissement()
    {
        return $this->container['code_cedex2_etablissement'];
    }

    /**
     * Sets code_cedex2_etablissement
     *
     * @param  $code_cedex2_etablissement Numéro de Cedex
     *
     * @return $this
     */
    public function setCodeCedex2Etablissement($code_cedex2_etablissement)
    {
        $this->container['code_cedex2_etablissement'] = $code_cedex2_etablissement;

        return $this;
    }

    /**
     * Gets libelle_cedex2_etablissement
     *
     * @return
     */
    public function getLibelleCedex2Etablissement()
    {
        return $this->container['libelle_cedex2_etablissement'];
    }

    /**
     * Sets libelle_cedex2_etablissement
     *
     * @param  $libelle_cedex2_etablissement Libellé correspondant au numéro de Cedex (variable codeCedexEtablissement)
     *
     * @return $this
     */
    public function setLibelleCedex2Etablissement($libelle_cedex2_etablissement)
    {
        $this->container['libelle_cedex2_etablissement'] = $libelle_cedex2_etablissement;

        return $this;
    }

    /**
     * Gets code_pays_etranger2_etablissement
     *
     * @return
     */
    public function getCodePaysEtranger2Etablissement()
    {
        return $this->container['code_pays_etranger2_etablissement'];
    }

    /**
     * Sets code_pays_etranger2_etablissement
     *
     * @param  $code_pays_etranger2_etablissement Code pays pour les établissements situés à l’étranger
     *
     * @return $this
     */
    public function setCodePaysEtranger2Etablissement($code_pays_etranger2_etablissement)
    {
        $this->container['code_pays_etranger2_etablissement'] = $code_pays_etranger2_etablissement;

        return $this;
    }

    /**
     * Gets libelle_pays_etranger2_etablissement
     *
     * @return
     */
    public function getLibellePaysEtranger2Etablissement()
    {
        return $this->container['libelle_pays_etranger2_etablissement'];
    }

    /**
     * Sets libelle_pays_etranger2_etablissement
     *
     * @param  $libelle_pays_etranger2_etablissement Libellé du pays pour les adresses à l’étranger
     *
     * @return $this
     */
    public function setLibellePaysEtranger2Etablissement($libelle_pays_etranger2_etablissement)
    {
        $this->container['libelle_pays_etranger2_etablissement'] = $libelle_pays_etranger2_etablissement;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
