<?php
/**
 * Adresse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Sirene\Client\Model;

use \ArrayAccess;
use \Sirene\Client\ObjectSerializer;

/**
 * Adresse Class Doc Comment
 *
 * @category Class
 * @description Ensemble des variables d&#x27;adresse d&#x27;un établissement
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Adresse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Adresse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'complement_adresse_etablissement' => '',
        'numero_voie_etablissement' => '',
        'indice_repetition_etablissement' => '',
        'dernier_numero_voie_etablissement' => '',
        'indice_repetition_dernier_numero_voie_etablissement' => '',
        'type_voie_etablissement' => '',
        'libelle_voie_etablissement' => '',
        'code_postal_etablissement' => '',
        'libelle_commune_etablissement' => '',
        'libelle_commune_etranger_etablissement' => '',
        'distribution_speciale_etablissement' => '',
        'code_commune_etablissement' => '',
        'code_cedex_etablissement' => '',
        'libelle_cedex_etablissement' => '',
        'code_pays_etranger_etablissement' => '',
        'libelle_pays_etranger_etablissement' => '',
        'identifiant_adresse_etablissement' => '',
        'coordonnee_lambert_abscisse_etablissement' => '',
        'coordonnee_lambert_ordonnee_etablissement' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'complement_adresse_etablissement' => null,
        'numero_voie_etablissement' => null,
        'indice_repetition_etablissement' => null,
        'dernier_numero_voie_etablissement' => null,
        'indice_repetition_dernier_numero_voie_etablissement' => null,
        'type_voie_etablissement' => null,
        'libelle_voie_etablissement' => null,
        'code_postal_etablissement' => null,
        'libelle_commune_etablissement' => null,
        'libelle_commune_etranger_etablissement' => null,
        'distribution_speciale_etablissement' => null,
        'code_commune_etablissement' => null,
        'code_cedex_etablissement' => null,
        'libelle_cedex_etablissement' => null,
        'code_pays_etranger_etablissement' => null,
        'libelle_pays_etranger_etablissement' => null,
        'identifiant_adresse_etablissement' => null,
        'coordonnee_lambert_abscisse_etablissement' => null,
        'coordonnee_lambert_ordonnee_etablissement' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'complement_adresse_etablissement' => 'complementAdresseEtablissement',
        'numero_voie_etablissement' => 'numeroVoieEtablissement',
        'indice_repetition_etablissement' => 'indiceRepetitionEtablissement',
        'dernier_numero_voie_etablissement' => 'dernierNumeroVoieEtablissement',
        'indice_repetition_dernier_numero_voie_etablissement' => 'indiceRepetitionDernierNumeroVoieEtablissement',
        'type_voie_etablissement' => 'typeVoieEtablissement',
        'libelle_voie_etablissement' => 'libelleVoieEtablissement',
        'code_postal_etablissement' => 'codePostalEtablissement',
        'libelle_commune_etablissement' => 'libelleCommuneEtablissement',
        'libelle_commune_etranger_etablissement' => 'libelleCommuneEtrangerEtablissement',
        'distribution_speciale_etablissement' => 'distributionSpecialeEtablissement',
        'code_commune_etablissement' => 'codeCommuneEtablissement',
        'code_cedex_etablissement' => 'codeCedexEtablissement',
        'libelle_cedex_etablissement' => 'libelleCedexEtablissement',
        'code_pays_etranger_etablissement' => 'codePaysEtrangerEtablissement',
        'libelle_pays_etranger_etablissement' => 'libellePaysEtrangerEtablissement',
        'identifiant_adresse_etablissement' => 'identifiantAdresseEtablissement',
        'coordonnee_lambert_abscisse_etablissement' => 'coordonneeLambertAbscisseEtablissement',
        'coordonnee_lambert_ordonnee_etablissement' => 'coordonneeLambertOrdonneeEtablissement'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'complement_adresse_etablissement' => 'setComplementAdresseEtablissement',
        'numero_voie_etablissement' => 'setNumeroVoieEtablissement',
        'indice_repetition_etablissement' => 'setIndiceRepetitionEtablissement',
        'dernier_numero_voie_etablissement' => 'setDernierNumeroVoieEtablissement',
        'indice_repetition_dernier_numero_voie_etablissement' => 'setIndiceRepetitionDernierNumeroVoieEtablissement',
        'type_voie_etablissement' => 'setTypeVoieEtablissement',
        'libelle_voie_etablissement' => 'setLibelleVoieEtablissement',
        'code_postal_etablissement' => 'setCodePostalEtablissement',
        'libelle_commune_etablissement' => 'setLibelleCommuneEtablissement',
        'libelle_commune_etranger_etablissement' => 'setLibelleCommuneEtrangerEtablissement',
        'distribution_speciale_etablissement' => 'setDistributionSpecialeEtablissement',
        'code_commune_etablissement' => 'setCodeCommuneEtablissement',
        'code_cedex_etablissement' => 'setCodeCedexEtablissement',
        'libelle_cedex_etablissement' => 'setLibelleCedexEtablissement',
        'code_pays_etranger_etablissement' => 'setCodePaysEtrangerEtablissement',
        'libelle_pays_etranger_etablissement' => 'setLibellePaysEtrangerEtablissement',
        'identifiant_adresse_etablissement' => 'setIdentifiantAdresseEtablissement',
        'coordonnee_lambert_abscisse_etablissement' => 'setCoordonneeLambertAbscisseEtablissement',
        'coordonnee_lambert_ordonnee_etablissement' => 'setCoordonneeLambertOrdonneeEtablissement'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'complement_adresse_etablissement' => 'getComplementAdresseEtablissement',
        'numero_voie_etablissement' => 'getNumeroVoieEtablissement',
        'indice_repetition_etablissement' => 'getIndiceRepetitionEtablissement',
        'dernier_numero_voie_etablissement' => 'getDernierNumeroVoieEtablissement',
        'indice_repetition_dernier_numero_voie_etablissement' => 'getIndiceRepetitionDernierNumeroVoieEtablissement',
        'type_voie_etablissement' => 'getTypeVoieEtablissement',
        'libelle_voie_etablissement' => 'getLibelleVoieEtablissement',
        'code_postal_etablissement' => 'getCodePostalEtablissement',
        'libelle_commune_etablissement' => 'getLibelleCommuneEtablissement',
        'libelle_commune_etranger_etablissement' => 'getLibelleCommuneEtrangerEtablissement',
        'distribution_speciale_etablissement' => 'getDistributionSpecialeEtablissement',
        'code_commune_etablissement' => 'getCodeCommuneEtablissement',
        'code_cedex_etablissement' => 'getCodeCedexEtablissement',
        'libelle_cedex_etablissement' => 'getLibelleCedexEtablissement',
        'code_pays_etranger_etablissement' => 'getCodePaysEtrangerEtablissement',
        'libelle_pays_etranger_etablissement' => 'getLibellePaysEtrangerEtablissement',
        'identifiant_adresse_etablissement' => 'getIdentifiantAdresseEtablissement',
        'coordonnee_lambert_abscisse_etablissement' => 'getCoordonneeLambertAbscisseEtablissement',
        'coordonnee_lambert_ordonnee_etablissement' => 'getCoordonneeLambertOrdonneeEtablissement'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['complement_adresse_etablissement'] = isset($data['complement_adresse_etablissement']) ? $data['complement_adresse_etablissement'] : null;
        $this->container['numero_voie_etablissement'] = isset($data['numero_voie_etablissement']) ? $data['numero_voie_etablissement'] : null;
        $this->container['indice_repetition_etablissement'] = isset($data['indice_repetition_etablissement']) ? $data['indice_repetition_etablissement'] : null;
        $this->container['dernier_numero_voie_etablissement'] = isset($data['dernier_numero_voie_etablissement']) ? $data['dernier_numero_voie_etablissement'] : null;
        $this->container['indice_repetition_dernier_numero_voie_etablissement'] = isset($data['indice_repetition_dernier_numero_voie_etablissement']) ? $data['indice_repetition_dernier_numero_voie_etablissement'] : null;
        $this->container['type_voie_etablissement'] = isset($data['type_voie_etablissement']) ? $data['type_voie_etablissement'] : null;
        $this->container['libelle_voie_etablissement'] = isset($data['libelle_voie_etablissement']) ? $data['libelle_voie_etablissement'] : null;
        $this->container['code_postal_etablissement'] = isset($data['code_postal_etablissement']) ? $data['code_postal_etablissement'] : null;
        $this->container['libelle_commune_etablissement'] = isset($data['libelle_commune_etablissement']) ? $data['libelle_commune_etablissement'] : null;
        $this->container['libelle_commune_etranger_etablissement'] = isset($data['libelle_commune_etranger_etablissement']) ? $data['libelle_commune_etranger_etablissement'] : null;
        $this->container['distribution_speciale_etablissement'] = isset($data['distribution_speciale_etablissement']) ? $data['distribution_speciale_etablissement'] : null;
        $this->container['code_commune_etablissement'] = isset($data['code_commune_etablissement']) ? $data['code_commune_etablissement'] : null;
        $this->container['code_cedex_etablissement'] = isset($data['code_cedex_etablissement']) ? $data['code_cedex_etablissement'] : null;
        $this->container['libelle_cedex_etablissement'] = isset($data['libelle_cedex_etablissement']) ? $data['libelle_cedex_etablissement'] : null;
        $this->container['code_pays_etranger_etablissement'] = isset($data['code_pays_etranger_etablissement']) ? $data['code_pays_etranger_etablissement'] : null;
        $this->container['libelle_pays_etranger_etablissement'] = isset($data['libelle_pays_etranger_etablissement']) ? $data['libelle_pays_etranger_etablissement'] : null;
        $this->container['identifiant_adresse_etablissement'] = isset($data['identifiant_adresse_etablissement']) ? $data['identifiant_adresse_etablissement'] : null;
        $this->container['coordonnee_lambert_abscisse_etablissement'] = isset($data['coordonnee_lambert_abscisse_etablissement']) ? $data['coordonnee_lambert_abscisse_etablissement'] : null;
        $this->container['coordonnee_lambert_ordonnee_etablissement'] = isset($data['coordonnee_lambert_ordonnee_etablissement']) ? $data['coordonnee_lambert_ordonnee_etablissement'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets complement_adresse_etablissement
     *
     * @return
     */
    public function getComplementAdresseEtablissement()
    {
        return $this->container['complement_adresse_etablissement'];
    }

    /**
     * Sets complement_adresse_etablissement
     *
     * @param  $complement_adresse_etablissement Complément d'adresse de l'établissement
     *
     * @return $this
     */
    public function setComplementAdresseEtablissement($complement_adresse_etablissement)
    {
        $this->container['complement_adresse_etablissement'] = $complement_adresse_etablissement;

        return $this;
    }

    /**
     * Gets numero_voie_etablissement
     *
     * @return
     */
    public function getNumeroVoieEtablissement()
    {
        return $this->container['numero_voie_etablissement'];
    }

    /**
     * Sets numero_voie_etablissement
     *
     * @param  $numero_voie_etablissement Numéro dans la voie
     *
     * @return $this
     */
    public function setNumeroVoieEtablissement($numero_voie_etablissement)
    {
        $this->container['numero_voie_etablissement'] = $numero_voie_etablissement;

        return $this;
    }

    /**
     * Gets indice_repetition_etablissement
     *
     * @return
     */
    public function getIndiceRepetitionEtablissement()
    {
        return $this->container['indice_repetition_etablissement'];
    }

    /**
     * Sets indice_repetition_etablissement
     *
     * @param  $indice_repetition_etablissement Indice de répétition dans la voie
     *
     * @return $this
     */
    public function setIndiceRepetitionEtablissement($indice_repetition_etablissement)
    {
        $this->container['indice_repetition_etablissement'] = $indice_repetition_etablissement;

        return $this;
    }

    /**
     * Gets dernier_numero_voie_etablissement
     *
     * @return
     */
    public function getDernierNumeroVoieEtablissement()
    {
        return $this->container['dernier_numero_voie_etablissement'];
    }

    /**
     * Sets dernier_numero_voie_etablissement
     *
     * @param  $dernier_numero_voie_etablissement Numéro de la dernière adresse dans la voie
     *
     * @return $this
     */
    public function setDernierNumeroVoieEtablissement($dernier_numero_voie_etablissement)
    {
        $this->container['dernier_numero_voie_etablissement'] = $dernier_numero_voie_etablissement;

        return $this;
    }

    /**
     * Gets indice_repetition_dernier_numero_voie_etablissement
     *
     * @return
     */
    public function getIndiceRepetitionDernierNumeroVoieEtablissement()
    {
        return $this->container['indice_repetition_dernier_numero_voie_etablissement'];
    }

    /**
     * Sets indice_repetition_dernier_numero_voie_etablissement
     *
     * @param  $indice_repetition_dernier_numero_voie_etablissement Indice de répétition de la dernière adresse dans la voie
     *
     * @return $this
     */
    public function setIndiceRepetitionDernierNumeroVoieEtablissement($indice_repetition_dernier_numero_voie_etablissement)
    {
        $this->container['indice_repetition_dernier_numero_voie_etablissement'] = $indice_repetition_dernier_numero_voie_etablissement;

        return $this;
    }

    /**
     * Gets type_voie_etablissement
     *
     * @return
     */
    public function getTypeVoieEtablissement()
    {
        return $this->container['type_voie_etablissement'];
    }

    /**
     * Sets type_voie_etablissement
     *
     * @param  $type_voie_etablissement Type de la voie
     *
     * @return $this
     */
    public function setTypeVoieEtablissement($type_voie_etablissement)
    {
        $this->container['type_voie_etablissement'] = $type_voie_etablissement;

        return $this;
    }

    /**
     * Gets libelle_voie_etablissement
     *
     * @return
     */
    public function getLibelleVoieEtablissement()
    {
        return $this->container['libelle_voie_etablissement'];
    }

    /**
     * Sets libelle_voie_etablissement
     *
     * @param  $libelle_voie_etablissement Libellé de la voie
     *
     * @return $this
     */
    public function setLibelleVoieEtablissement($libelle_voie_etablissement)
    {
        $this->container['libelle_voie_etablissement'] = $libelle_voie_etablissement;

        return $this;
    }

    /**
     * Gets code_postal_etablissement
     *
     * @return
     */
    public function getCodePostalEtablissement()
    {
        return $this->container['code_postal_etablissement'];
    }

    /**
     * Sets code_postal_etablissement
     *
     * @param  $code_postal_etablissement Code postal
     *
     * @return $this
     */
    public function setCodePostalEtablissement($code_postal_etablissement)
    {
        $this->container['code_postal_etablissement'] = $code_postal_etablissement;

        return $this;
    }

    /**
     * Gets libelle_commune_etablissement
     *
     * @return
     */
    public function getLibelleCommuneEtablissement()
    {
        return $this->container['libelle_commune_etablissement'];
    }

    /**
     * Sets libelle_commune_etablissement
     *
     * @param  $libelle_commune_etablissement Libellé de la commune pour les adresses en France
     *
     * @return $this
     */
    public function setLibelleCommuneEtablissement($libelle_commune_etablissement)
    {
        $this->container['libelle_commune_etablissement'] = $libelle_commune_etablissement;

        return $this;
    }

    /**
     * Gets libelle_commune_etranger_etablissement
     *
     * @return
     */
    public function getLibelleCommuneEtrangerEtablissement()
    {
        return $this->container['libelle_commune_etranger_etablissement'];
    }

    /**
     * Sets libelle_commune_etranger_etablissement
     *
     * @param  $libelle_commune_etranger_etablissement Libellé complémentaire pour une adresse à l'étranger
     *
     * @return $this
     */
    public function setLibelleCommuneEtrangerEtablissement($libelle_commune_etranger_etablissement)
    {
        $this->container['libelle_commune_etranger_etablissement'] = $libelle_commune_etranger_etablissement;

        return $this;
    }

    /**
     * Gets distribution_speciale_etablissement
     *
     * @return
     */
    public function getDistributionSpecialeEtablissement()
    {
        return $this->container['distribution_speciale_etablissement'];
    }

    /**
     * Sets distribution_speciale_etablissement
     *
     * @param  $distribution_speciale_etablissement Distribution spéciale (BP par ex)
     *
     * @return $this
     */
    public function setDistributionSpecialeEtablissement($distribution_speciale_etablissement)
    {
        $this->container['distribution_speciale_etablissement'] = $distribution_speciale_etablissement;

        return $this;
    }

    /**
     * Gets code_commune_etablissement
     *
     * @return
     */
    public function getCodeCommuneEtablissement()
    {
        return $this->container['code_commune_etablissement'];
    }

    /**
     * Sets code_commune_etablissement
     *
     * @param  $code_commune_etablissement Code commune de localisation de l’établissement hors établissements situés à l’étranger (Le code commune est défini dans le <a href='https://www.insee.fr/fr/information/2028028'>code officiel géographique (COG)</a>)
     *
     * @return $this
     */
    public function setCodeCommuneEtablissement($code_commune_etablissement)
    {
        $this->container['code_commune_etablissement'] = $code_commune_etablissement;

        return $this;
    }

    /**
     * Gets code_cedex_etablissement
     *
     * @return
     */
    public function getCodeCedexEtablissement()
    {
        return $this->container['code_cedex_etablissement'];
    }

    /**
     * Sets code_cedex_etablissement
     *
     * @param  $code_cedex_etablissement Numéro de Cedex
     *
     * @return $this
     */
    public function setCodeCedexEtablissement($code_cedex_etablissement)
    {
        $this->container['code_cedex_etablissement'] = $code_cedex_etablissement;

        return $this;
    }

    /**
     * Gets libelle_cedex_etablissement
     *
     * @return
     */
    public function getLibelleCedexEtablissement()
    {
        return $this->container['libelle_cedex_etablissement'];
    }

    /**
     * Sets libelle_cedex_etablissement
     *
     * @param  $libelle_cedex_etablissement Libellé correspondant au numéro de Cedex (variable codeCedexEtablissement)
     *
     * @return $this
     */
    public function setLibelleCedexEtablissement($libelle_cedex_etablissement)
    {
        $this->container['libelle_cedex_etablissement'] = $libelle_cedex_etablissement;

        return $this;
    }

    /**
     * Gets code_pays_etranger_etablissement
     *
     * @return
     */
    public function getCodePaysEtrangerEtablissement()
    {
        return $this->container['code_pays_etranger_etablissement'];
    }

    /**
     * Sets code_pays_etranger_etablissement
     *
     * @param  $code_pays_etranger_etablissement Code pays pour les établissements situés à l’étranger
     *
     * @return $this
     */
    public function setCodePaysEtrangerEtablissement($code_pays_etranger_etablissement)
    {
        $this->container['code_pays_etranger_etablissement'] = $code_pays_etranger_etablissement;

        return $this;
    }

    /**
     * Gets libelle_pays_etranger_etablissement
     *
     * @return
     */
    public function getLibellePaysEtrangerEtablissement()
    {
        return $this->container['libelle_pays_etranger_etablissement'];
    }

    /**
     * Sets libelle_pays_etranger_etablissement
     *
     * @param  $libelle_pays_etranger_etablissement Libellé du pays pour les adresses à l’étranger
     *
     * @return $this
     */
    public function setLibellePaysEtrangerEtablissement($libelle_pays_etranger_etablissement)
    {
        $this->container['libelle_pays_etranger_etablissement'] = $libelle_pays_etranger_etablissement;

        return $this;
    }

    /**
     * Gets identifiant_adresse_etablissement
     *
     * @return
     */
    public function getIdentifiantAdresseEtablissement()
    {
        return $this->container['identifiant_adresse_etablissement'];
    }

    /**
     * Sets identifiant_adresse_etablissement
     *
     * @param  $identifiant_adresse_etablissement IdentifiantAdresseEtablissement
     *
     * @return $this
     */
    public function setIdentifiantAdresseEtablissement($identifiant_adresse_etablissement)
    {
        $this->container['identifiant_adresse_etablissement'] = $identifiant_adresse_etablissement;

        return $this;
    }

    /**
     * Gets coordonnee_lambert_abscisse_etablissement
     *
     * @return
     */
    public function getCoordonneeLambertAbscisseEtablissement()
    {
        return $this->container['coordonnee_lambert_abscisse_etablissement'];
    }

    /**
     * Sets coordonnee_lambert_abscisse_etablissement
     *
     * @param  $coordonnee_lambert_abscisse_etablissement coordonneeLambertAbscisseEtablissement
     *
     * @return $this
     */
    public function setCoordonneeLambertAbscisseEtablissement($coordonnee_lambert_abscisse_etablissement)
    {
        $this->container['coordonnee_lambert_abscisse_etablissement'] = $coordonnee_lambert_abscisse_etablissement;

        return $this;
    }

    /**
     * Gets coordonnee_lambert_ordonnee_etablissement
     *
     * @return
     */
    public function getCoordonneeLambertOrdonneeEtablissement()
    {
        return $this->container['coordonnee_lambert_ordonnee_etablissement'];
    }

    /**
     * Sets coordonnee_lambert_ordonnee_etablissement
     *
     * @param  $coordonnee_lambert_ordonnee_etablissement coordonneeLambertOrdonneeEtablissement
     *
     * @return $this
     */
    public function setCoordonneeLambertOrdonneeEtablissement($coordonnee_lambert_ordonnee_etablissement)
    {
        $this->container['coordonnee_lambert_ordonnee_etablissement'] = $coordonnee_lambert_ordonnee_etablissement;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
