<?php
/**
 * Header
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Sirene\Client\Model;

use \ArrayAccess;
use \Sirene\Client\ObjectSerializer;

/**
 * Header Class Doc Comment
 *
 * @category Class
 * @description Informations générales sur le résultat de la requête
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Header implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Header';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'statut' => '',
        'message' => '',
        'total' => '',
        'debut' => '',
        'nombre' => '',
        'curseur' => '',
        'curseur_suivant' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'statut' => 'int32',
        'message' => null,
        'total' => 'int64',
        'debut' => 'int64',
        'nombre' => 'int64',
        'curseur' => null,
        'curseur_suivant' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'statut' => 'statut',
        'message' => 'message',
        'total' => 'total',
        'debut' => 'debut',
        'nombre' => 'nombre',
        'curseur' => 'curseur',
        'curseur_suivant' => 'curseurSuivant'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'statut' => 'setStatut',
        'message' => 'setMessage',
        'total' => 'setTotal',
        'debut' => 'setDebut',
        'nombre' => 'setNombre',
        'curseur' => 'setCurseur',
        'curseur_suivant' => 'setCurseurSuivant'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'statut' => 'getStatut',
        'message' => 'getMessage',
        'total' => 'getTotal',
        'debut' => 'getDebut',
        'nombre' => 'getNombre',
        'curseur' => 'getCurseur',
        'curseur_suivant' => 'getCurseurSuivant'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['statut'] = isset($data['statut']) ? $data['statut'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['total'] = isset($data['total']) ? $data['total'] : null;
        $this->container['debut'] = isset($data['debut']) ? $data['debut'] : null;
        $this->container['nombre'] = isset($data['nombre']) ? $data['nombre'] : null;
        $this->container['curseur'] = isset($data['curseur']) ? $data['curseur'] : null;
        $this->container['curseur_suivant'] = isset($data['curseur_suivant']) ? $data['curseur_suivant'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets statut
     *
     * @return 
     */
    public function getStatut()
    {
        return $this->container['statut'];
    }

    /**
     * Sets statut
     *
     * @param  $statut Égal au status de la réponse HTTP
     *
     * @return $this
     */
    public function setStatut($statut)
    {
        $this->container['statut'] = $statut;

        return $this;
    }

    /**
     * Gets message
     *
     * @return 
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param  $message En cas d'erreur, message indiquant la cause de l'erreur. OK sinon
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets total
     *
     * @return 
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param  $total Nombre total des éléments répondant à la requête
     *
     * @return $this
     */
    public function setTotal($total)
    {
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets debut
     *
     * @return 
     */
    public function getDebut()
    {
        return $this->container['debut'];
    }

    /**
     * Sets debut
     *
     * @param  $debut Numéro du premier élément fourni, défaut à 0, commence à 0
     *
     * @return $this
     */
    public function setDebut($debut)
    {
        $this->container['debut'] = $debut;

        return $this;
    }

    /**
     * Gets nombre
     *
     * @return 
     */
    public function getNombre()
    {
        return $this->container['nombre'];
    }

    /**
     * Sets nombre
     *
     * @param  $nombre Nombre d'éléments fournis, défaut à 20
     *
     * @return $this
     */
    public function setNombre($nombre)
    {
        $this->container['nombre'] = $nombre;

        return $this;
    }

    /**
     * Gets curseur
     *
     * @return 
     */
    public function getCurseur()
    {
        return $this->container['curseur'];
    }

    /**
     * Sets curseur
     *
     * @param  $curseur Curseur passé en argument dans la requête de l'utilisateur, utilisé pour la pagination profonde
     *
     * @return $this
     */
    public function setCurseur($curseur)
    {
        $this->container['curseur'] = $curseur;

        return $this;
    }

    /**
     * Gets curseur_suivant
     *
     * @return 
     */
    public function getCurseurSuivant()
    {
        return $this->container['curseur_suivant'];
    }

    /**
     * Sets curseur_suivant
     *
     * @param  $curseur_suivant Curseur suivant pour accéder à la suite des résultat lorsqu'on utilise la pagination profonde
     *
     * @return $this
     */
    public function setCurseurSuivant($curseur_suivant)
    {
        $this->container['curseur_suivant'] = $curseur_suivant;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
