<?php
/**
 * UniteLegale
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Sirene\Client\Model;

use \ArrayAccess;
use \Sirene\Client\ObjectSerializer;

/**
 * UniteLegale Class Doc Comment
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UniteLegale implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UniteLegale';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'score' => '',
        'siren' => '',
        'statut_diffusion_unite_legale' => '',
        'unite_purgee_unite_legale' => '',
        'date_creation_unite_legale' => '',
        'date_naissance_unite_legale' => '',
        'code_commune_naissance_unite_legale' => '',
        'code_pays_naissance_unite_legale' => '',
        'libelle_nationalite_unite_legale' => '',
        'identifiant_association_unite_legale' => '',
        'tranche_effectifs_unite_legale' => '',
        'annee_effectifs_unite_legale' => '',
        'date_dernier_traitement_unite_legale' => '',
        'nombre_periodes_unite_legale' => '',
        'categorie_entreprise' => '',
        'annee_categorie_entreprise' => '',
        'sigle_unite_legale' => '',
        'sexe_unite_legale' => '',
        'prenom1_unite_legale' => '',
        'prenom2_unite_legale' => '',
        'prenom3_unite_legale' => '',
        'prenom4_unite_legale' => '',
        'prenom_usuel_unite_legale' => '',
        'pseudonyme_unite_legale' => '',
        'periodes_unite_legale' => ''
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'score' => 'float',
        'siren' => null,
        'statut_diffusion_unite_legale' => null,
        'unite_purgee_unite_legale' => null,
        'date_creation_unite_legale' => 'date',
        'date_naissance_unite_legale' => null,
        'code_commune_naissance_unite_legale' => null,
        'code_pays_naissance_unite_legale' => null,
        'libelle_nationalite_unite_legale' => null,
        'identifiant_association_unite_legale' => null,
        'tranche_effectifs_unite_legale' => null,
        'annee_effectifs_unite_legale' => null,
        'date_dernier_traitement_unite_legale' => 'AAAA-MM-JJTHH:MM:SS',
        'nombre_periodes_unite_legale' => 'int32',
        'categorie_entreprise' => null,
        'annee_categorie_entreprise' => null,
        'sigle_unite_legale' => null,
        'sexe_unite_legale' => null,
        'prenom1_unite_legale' => null,
        'prenom2_unite_legale' => null,
        'prenom3_unite_legale' => null,
        'prenom4_unite_legale' => null,
        'prenom_usuel_unite_legale' => null,
        'pseudonyme_unite_legale' => null,
        'periodes_unite_legale' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'score' => 'score',
        'siren' => 'siren',
        'statut_diffusion_unite_legale' => 'statutDiffusionUniteLegale',
        'unite_purgee_unite_legale' => 'unitePurgeeUniteLegale',
        'date_creation_unite_legale' => 'dateCreationUniteLegale',
        'date_naissance_unite_legale' => 'dateNaissanceUniteLegale',
        'code_commune_naissance_unite_legale' => 'codeCommuneNaissanceUniteLegale',
        'code_pays_naissance_unite_legale' => 'codePaysNaissanceUniteLegale',
        'libelle_nationalite_unite_legale' => 'libelleNationaliteUniteLegale',
        'identifiant_association_unite_legale' => 'identifiantAssociationUniteLegale',
        'tranche_effectifs_unite_legale' => 'trancheEffectifsUniteLegale',
        'annee_effectifs_unite_legale' => 'anneeEffectifsUniteLegale',
        'date_dernier_traitement_unite_legale' => 'dateDernierTraitementUniteLegale',
        'nombre_periodes_unite_legale' => 'nombrePeriodesUniteLegale',
        'categorie_entreprise' => 'categorieEntreprise',
        'annee_categorie_entreprise' => 'anneeCategorieEntreprise',
        'sigle_unite_legale' => 'sigleUniteLegale',
        'sexe_unite_legale' => 'sexeUniteLegale',
        'prenom1_unite_legale' => 'prenom1UniteLegale',
        'prenom2_unite_legale' => 'prenom2UniteLegale',
        'prenom3_unite_legale' => 'prenom3UniteLegale',
        'prenom4_unite_legale' => 'prenom4UniteLegale',
        'prenom_usuel_unite_legale' => 'prenomUsuelUniteLegale',
        'pseudonyme_unite_legale' => 'pseudonymeUniteLegale',
        'periodes_unite_legale' => 'periodesUniteLegale'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'score' => 'setScore',
        'siren' => 'setSiren',
        'statut_diffusion_unite_legale' => 'setStatutDiffusionUniteLegale',
        'unite_purgee_unite_legale' => 'setUnitePurgeeUniteLegale',
        'date_creation_unite_legale' => 'setDateCreationUniteLegale',
        'date_naissance_unite_legale' => 'setDateNaissanceUniteLegale',
        'code_commune_naissance_unite_legale' => 'setCodeCommuneNaissanceUniteLegale',
        'code_pays_naissance_unite_legale' => 'setCodePaysNaissanceUniteLegale',
        'libelle_nationalite_unite_legale' => 'setLibelleNationaliteUniteLegale',
        'identifiant_association_unite_legale' => 'setIdentifiantAssociationUniteLegale',
        'tranche_effectifs_unite_legale' => 'setTrancheEffectifsUniteLegale',
        'annee_effectifs_unite_legale' => 'setAnneeEffectifsUniteLegale',
        'date_dernier_traitement_unite_legale' => 'setDateDernierTraitementUniteLegale',
        'nombre_periodes_unite_legale' => 'setNombrePeriodesUniteLegale',
        'categorie_entreprise' => 'setCategorieEntreprise',
        'annee_categorie_entreprise' => 'setAnneeCategorieEntreprise',
        'sigle_unite_legale' => 'setSigleUniteLegale',
        'sexe_unite_legale' => 'setSexeUniteLegale',
        'prenom1_unite_legale' => 'setPrenom1UniteLegale',
        'prenom2_unite_legale' => 'setPrenom2UniteLegale',
        'prenom3_unite_legale' => 'setPrenom3UniteLegale',
        'prenom4_unite_legale' => 'setPrenom4UniteLegale',
        'prenom_usuel_unite_legale' => 'setPrenomUsuelUniteLegale',
        'pseudonyme_unite_legale' => 'setPseudonymeUniteLegale',
        'periodes_unite_legale' => 'setPeriodesUniteLegale'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'score' => 'getScore',
        'siren' => 'getSiren',
        'statut_diffusion_unite_legale' => 'getStatutDiffusionUniteLegale',
        'unite_purgee_unite_legale' => 'getUnitePurgeeUniteLegale',
        'date_creation_unite_legale' => 'getDateCreationUniteLegale',
        'date_naissance_unite_legale' => 'getDateNaissanceUniteLegale',
        'code_commune_naissance_unite_legale' => 'getCodeCommuneNaissanceUniteLegale',
        'code_pays_naissance_unite_legale' => 'getCodePaysNaissanceUniteLegale',
        'libelle_nationalite_unite_legale' => 'getLibelleNationaliteUniteLegale',
        'identifiant_association_unite_legale' => 'getIdentifiantAssociationUniteLegale',
        'tranche_effectifs_unite_legale' => 'getTrancheEffectifsUniteLegale',
        'annee_effectifs_unite_legale' => 'getAnneeEffectifsUniteLegale',
        'date_dernier_traitement_unite_legale' => 'getDateDernierTraitementUniteLegale',
        'nombre_periodes_unite_legale' => 'getNombrePeriodesUniteLegale',
        'categorie_entreprise' => 'getCategorieEntreprise',
        'annee_categorie_entreprise' => 'getAnneeCategorieEntreprise',
        'sigle_unite_legale' => 'getSigleUniteLegale',
        'sexe_unite_legale' => 'getSexeUniteLegale',
        'prenom1_unite_legale' => 'getPrenom1UniteLegale',
        'prenom2_unite_legale' => 'getPrenom2UniteLegale',
        'prenom3_unite_legale' => 'getPrenom3UniteLegale',
        'prenom4_unite_legale' => 'getPrenom4UniteLegale',
        'prenom_usuel_unite_legale' => 'getPrenomUsuelUniteLegale',
        'pseudonyme_unite_legale' => 'getPseudonymeUniteLegale',
        'periodes_unite_legale' => 'getPeriodesUniteLegale'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['score'] = isset($data['score']) ? $data['score'] : null;
        $this->container['siren'] = isset($data['siren']) ? $data['siren'] : null;
        $this->container['statut_diffusion_unite_legale'] = isset($data['statut_diffusion_unite_legale']) ? $data['statut_diffusion_unite_legale'] : null;
        $this->container['unite_purgee_unite_legale'] = isset($data['unite_purgee_unite_legale']) ? $data['unite_purgee_unite_legale'] : null;
        $this->container['date_creation_unite_legale'] = isset($data['date_creation_unite_legale']) ? $data['date_creation_unite_legale'] : null;
        $this->container['date_naissance_unite_legale'] = isset($data['date_naissance_unite_legale']) ? $data['date_naissance_unite_legale'] : null;
        $this->container['code_commune_naissance_unite_legale'] = isset($data['code_commune_naissance_unite_legale']) ? $data['code_commune_naissance_unite_legale'] : null;
        $this->container['code_pays_naissance_unite_legale'] = isset($data['code_pays_naissance_unite_legale']) ? $data['code_pays_naissance_unite_legale'] : null;
        $this->container['libelle_nationalite_unite_legale'] = isset($data['libelle_nationalite_unite_legale']) ? $data['libelle_nationalite_unite_legale'] : null;
        $this->container['identifiant_association_unite_legale'] = isset($data['identifiant_association_unite_legale']) ? $data['identifiant_association_unite_legale'] : null;
        $this->container['tranche_effectifs_unite_legale'] = isset($data['tranche_effectifs_unite_legale']) ? $data['tranche_effectifs_unite_legale'] : null;
        $this->container['annee_effectifs_unite_legale'] = isset($data['annee_effectifs_unite_legale']) ? $data['annee_effectifs_unite_legale'] : null;
        $this->container['date_dernier_traitement_unite_legale'] = isset($data['date_dernier_traitement_unite_legale']) ? $data['date_dernier_traitement_unite_legale'] : null;
        $this->container['nombre_periodes_unite_legale'] = isset($data['nombre_periodes_unite_legale']) ? $data['nombre_periodes_unite_legale'] : null;
        $this->container['categorie_entreprise'] = isset($data['categorie_entreprise']) ? $data['categorie_entreprise'] : null;
        $this->container['annee_categorie_entreprise'] = isset($data['annee_categorie_entreprise']) ? $data['annee_categorie_entreprise'] : null;
        $this->container['sigle_unite_legale'] = isset($data['sigle_unite_legale']) ? $data['sigle_unite_legale'] : null;
        $this->container['sexe_unite_legale'] = isset($data['sexe_unite_legale']) ? $data['sexe_unite_legale'] : null;
        $this->container['prenom1_unite_legale'] = isset($data['prenom1_unite_legale']) ? $data['prenom1_unite_legale'] : null;
        $this->container['prenom2_unite_legale'] = isset($data['prenom2_unite_legale']) ? $data['prenom2_unite_legale'] : null;
        $this->container['prenom3_unite_legale'] = isset($data['prenom3_unite_legale']) ? $data['prenom3_unite_legale'] : null;
        $this->container['prenom4_unite_legale'] = isset($data['prenom4_unite_legale']) ? $data['prenom4_unite_legale'] : null;
        $this->container['prenom_usuel_unite_legale'] = isset($data['prenom_usuel_unite_legale']) ? $data['prenom_usuel_unite_legale'] : null;
        $this->container['pseudonyme_unite_legale'] = isset($data['pseudonyme_unite_legale']) ? $data['pseudonyme_unite_legale'] : null;
        $this->container['periodes_unite_legale'] = isset($data['periodes_unite_legale']) ? $data['periodes_unite_legale'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets score
     *
     * @return 
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param  $score Score de l'élément parmi l'ensemble des éléments répondant à la requête, plus le score est élevé, plus l'élément est haut placé. Le score n'a pas de signification en dehors de la requête et n'est pas comparable aux score d'autres requêtes
     *
     * @return $this
     */
    public function setScore($score)
    {
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets siren
     *
     * @return 
     */
    public function getSiren()
    {
        return $this->container['siren'];
    }

    /**
     * Sets siren
     *
     * @param  $siren Numéro Siren de l'entreprise, toujours renseigné
     *
     * @return $this
     */
    public function setSiren($siren)
    {
        $this->container['siren'] = $siren;

        return $this;
    }

    /**
     * Gets statut_diffusion_unite_legale
     *
     * @return 
     */
    public function getStatutDiffusionUniteLegale()
    {
        return $this->container['statut_diffusion_unite_legale'];
    }

    /**
     * Sets statut_diffusion_unite_legale
     *
     * @param  $statut_diffusion_unite_legale Statut de diffusion de l’unité légale
     *
     * @return $this
     */
    public function setStatutDiffusionUniteLegale($statut_diffusion_unite_legale)
    {
        $this->container['statut_diffusion_unite_legale'] = $statut_diffusion_unite_legale;

        return $this;
    }

    /**
     * Gets unite_purgee_unite_legale
     *
     * @return 
     */
    public function getUnitePurgeeUniteLegale()
    {
        return $this->container['unite_purgee_unite_legale'];
    }

    /**
     * Sets unite_purgee_unite_legale
     *
     * @param  $unite_purgee_unite_legale True si l'unité est une unité purgée
     *
     * @return $this
     */
    public function setUnitePurgeeUniteLegale($unite_purgee_unite_legale)
    {
        $this->container['unite_purgee_unite_legale'] = $unite_purgee_unite_legale;

        return $this;
    }

    /**
     * Gets date_creation_unite_legale
     *
     * @return 
     */
    public function getDateCreationUniteLegale()
    {
        return $this->container['date_creation_unite_legale'];
    }

    /**
     * Sets date_creation_unite_legale
     *
     * @param  $date_creation_unite_legale Date de création de l'unité légale
     *
     * @return $this
     */
    public function setDateCreationUniteLegale($date_creation_unite_legale)
    {
        $this->container['date_creation_unite_legale'] = $date_creation_unite_legale;

        return $this;
    }

    /**
     * Gets date_naissance_unite_legale
     *
     * @return 
     */
    public function getDateNaissanceUniteLegale()
    {
        return $this->container['date_naissance_unite_legale'];
    }

    /**
     * Sets date_naissance_unite_legale
     *
     * @param  $date_naissance_unite_legale L’accès à ces données est soumis à une démarche auprès de la Commission nationale de l’informatique et des libertés. Date de naissance pour la personne physique sinon null
     *
     * @return $this
     */
    public function setDateNaissanceUniteLegale($date_naissance_unite_legale)
    {
        $this->container['date_naissance_unite_legale'] = $date_naissance_unite_legale;

        return $this;
    }

    /**
     * Gets code_commune_naissance_unite_legale
     *
     * @return 
     */
    public function getCodeCommuneNaissanceUniteLegale()
    {
        return $this->container['code_commune_naissance_unite_legale'];
    }

    /**
     * Sets code_commune_naissance_unite_legale
     *
     * @param  $code_commune_naissance_unite_legale L’accès à ces données est soumis à une démarche auprès de la Commission nationale de l’informatique et des libertés. Code commune de naissance pour les personnes physiques, null pour les personnes morales et les personnes physiques nées à l’étranger
     *
     * @return $this
     */
    public function setCodeCommuneNaissanceUniteLegale($code_commune_naissance_unite_legale)
    {
        $this->container['code_commune_naissance_unite_legale'] = $code_commune_naissance_unite_legale;

        return $this;
    }

    /**
     * Gets code_pays_naissance_unite_legale
     *
     * @return 
     */
    public function getCodePaysNaissanceUniteLegale()
    {
        return $this->container['code_pays_naissance_unite_legale'];
    }

    /**
     * Sets code_pays_naissance_unite_legale
     *
     * @param  $code_pays_naissance_unite_legale L’accès à ces données est soumis à une démarche auprès de la Commission nationale de l’informatique et des libertés. Code pays de naissance pour les personnes physiques nées à l’étranger, null sinon
     *
     * @return $this
     */
    public function setCodePaysNaissanceUniteLegale($code_pays_naissance_unite_legale)
    {
        $this->container['code_pays_naissance_unite_legale'] = $code_pays_naissance_unite_legale;

        return $this;
    }

    /**
     * Gets libelle_nationalite_unite_legale
     *
     * @return 
     */
    public function getLibelleNationaliteUniteLegale()
    {
        return $this->container['libelle_nationalite_unite_legale'];
    }

    /**
     * Sets libelle_nationalite_unite_legale
     *
     * @param  $libelle_nationalite_unite_legale L’accès à ces données est soumis à une démarche auprès de la Commission nationale de l’informatique et des libertés. Nationalité pour les personnes physiques
     *
     * @return $this
     */
    public function setLibelleNationaliteUniteLegale($libelle_nationalite_unite_legale)
    {
        $this->container['libelle_nationalite_unite_legale'] = $libelle_nationalite_unite_legale;

        return $this;
    }

    /**
     * Gets identifiant_association_unite_legale
     *
     * @return 
     */
    public function getIdentifiantAssociationUniteLegale()
    {
        return $this->container['identifiant_association_unite_legale'];
    }

    /**
     * Sets identifiant_association_unite_legale
     *
     * @param  $identifiant_association_unite_legale Numéro au Répertoire National des Associations
     *
     * @return $this
     */
    public function setIdentifiantAssociationUniteLegale($identifiant_association_unite_legale)
    {
        $this->container['identifiant_association_unite_legale'] = $identifiant_association_unite_legale;

        return $this;
    }

    /**
     * Gets tranche_effectifs_unite_legale
     *
     * @return 
     */
    public function getTrancheEffectifsUniteLegale()
    {
        return $this->container['tranche_effectifs_unite_legale'];
    }

    /**
     * Sets tranche_effectifs_unite_legale
     *
     * @param  $tranche_effectifs_unite_legale Tranche d'effectif salarié de l'unité légale, valorisé uniquement si l'année correspondante est supérieure ou égale à l'année d'interrogation-3 (sinon, NN)
     *
     * @return $this
     */
    public function setTrancheEffectifsUniteLegale($tranche_effectifs_unite_legale)
    {
        $this->container['tranche_effectifs_unite_legale'] = $tranche_effectifs_unite_legale;

        return $this;
    }

    /**
     * Gets annee_effectifs_unite_legale
     *
     * @return 
     */
    public function getAnneeEffectifsUniteLegale()
    {
        return $this->container['annee_effectifs_unite_legale'];
    }

    /**
     * Sets annee_effectifs_unite_legale
     *
     * @param  $annee_effectifs_unite_legale Année de validité de la tranche d'effectif salarié de l'unité légale, valorisée uniquement si l'année est supérieure ou égale à l'année d'interrogation-3 (sinon, null)
     *
     * @return $this
     */
    public function setAnneeEffectifsUniteLegale($annee_effectifs_unite_legale)
    {
        $this->container['annee_effectifs_unite_legale'] = $annee_effectifs_unite_legale;

        return $this;
    }

    /**
     * Gets date_dernier_traitement_unite_legale
     *
     * @return 
     */
    public function getDateDernierTraitementUniteLegale()
    {
        return $this->container['date_dernier_traitement_unite_legale'];
    }

    /**
     * Sets date_dernier_traitement_unite_legale
     *
     * @param  $date_dernier_traitement_unite_legale Date de la dernière mise à jour effectuée au répertoire Sirene sur le Siren concerné
     *
     * @return $this
     */
    public function setDateDernierTraitementUniteLegale($date_dernier_traitement_unite_legale)
    {
        $this->container['date_dernier_traitement_unite_legale'] = $date_dernier_traitement_unite_legale;

        return $this;
    }

    /**
     * Gets nombre_periodes_unite_legale
     *
     * @return 
     */
    public function getNombrePeriodesUniteLegale()
    {
        return $this->container['nombre_periodes_unite_legale'];
    }

    /**
     * Sets nombre_periodes_unite_legale
     *
     * @param  $nombre_periodes_unite_legale Nombre de périodes dans la vie de l'unité légale
     *
     * @return $this
     */
    public function setNombrePeriodesUniteLegale($nombre_periodes_unite_legale)
    {
        $this->container['nombre_periodes_unite_legale'] = $nombre_periodes_unite_legale;

        return $this;
    }

    /**
     * Gets categorie_entreprise
     *
     * @return 
     */
    public function getCategorieEntreprise()
    {
        return $this->container['categorie_entreprise'];
    }

    /**
     * Sets categorie_entreprise
     *
     * @param  $categorie_entreprise Catégorie à laquelle appartient l'entreprise : Petite ou moyenne entreprise, Entreprise de taille intermédiaire, Grande entreprise
     *
     * @return $this
     */
    public function setCategorieEntreprise($categorie_entreprise)
    {
        $this->container['categorie_entreprise'] = $categorie_entreprise;

        return $this;
    }

    /**
     * Gets annee_categorie_entreprise
     *
     * @return 
     */
    public function getAnneeCategorieEntreprise()
    {
        return $this->container['annee_categorie_entreprise'];
    }

    /**
     * Sets annee_categorie_entreprise
     *
     * @param  $annee_categorie_entreprise Année de validité de la catégorie d'entreprise
     *
     * @return $this
     */
    public function setAnneeCategorieEntreprise($annee_categorie_entreprise)
    {
        $this->container['annee_categorie_entreprise'] = $annee_categorie_entreprise;

        return $this;
    }

    /**
     * Gets sigle_unite_legale
     *
     * @return 
     */
    public function getSigleUniteLegale()
    {
        return $this->container['sigle_unite_legale'];
    }

    /**
     * Sets sigle_unite_legale
     *
     * @param  $sigle_unite_legale Sigle de l'unité légale
     *
     * @return $this
     */
    public function setSigleUniteLegale($sigle_unite_legale)
    {
        $this->container['sigle_unite_legale'] = $sigle_unite_legale;

        return $this;
    }

    /**
     * Gets sexe_unite_legale
     *
     * @return 
     */
    public function getSexeUniteLegale()
    {
        return $this->container['sexe_unite_legale'];
    }

    /**
     * Sets sexe_unite_legale
     *
     * @param  $sexe_unite_legale Sexe pour les personnes physiques sinon null
     *
     * @return $this
     */
    public function setSexeUniteLegale($sexe_unite_legale)
    {
        $this->container['sexe_unite_legale'] = $sexe_unite_legale;

        return $this;
    }

    /**
     * Gets prenom1_unite_legale
     *
     * @return 
     */
    public function getPrenom1UniteLegale()
    {
        return $this->container['prenom1_unite_legale'];
    }

    /**
     * Sets prenom1_unite_legale
     *
     * @param  $prenom1_unite_legale Premier prénom déclaré pour une personne physique, peut être null dans le cas d'une unité purgée
     *
     * @return $this
     */
    public function setPrenom1UniteLegale($prenom1_unite_legale)
    {
        $this->container['prenom1_unite_legale'] = $prenom1_unite_legale;

        return $this;
    }

    /**
     * Gets prenom2_unite_legale
     *
     * @return 
     */
    public function getPrenom2UniteLegale()
    {
        return $this->container['prenom2_unite_legale'];
    }

    /**
     * Sets prenom2_unite_legale
     *
     * @param  $prenom2_unite_legale Deuxième prénom déclaré pour une personne physique
     *
     * @return $this
     */
    public function setPrenom2UniteLegale($prenom2_unite_legale)
    {
        $this->container['prenom2_unite_legale'] = $prenom2_unite_legale;

        return $this;
    }

    /**
     * Gets prenom3_unite_legale
     *
     * @return 
     */
    public function getPrenom3UniteLegale()
    {
        return $this->container['prenom3_unite_legale'];
    }

    /**
     * Sets prenom3_unite_legale
     *
     * @param  $prenom3_unite_legale Troisième prénom déclaré pour une personne physique
     *
     * @return $this
     */
    public function setPrenom3UniteLegale($prenom3_unite_legale)
    {
        $this->container['prenom3_unite_legale'] = $prenom3_unite_legale;

        return $this;
    }

    /**
     * Gets prenom4_unite_legale
     *
     * @return 
     */
    public function getPrenom4UniteLegale()
    {
        return $this->container['prenom4_unite_legale'];
    }

    /**
     * Sets prenom4_unite_legale
     *
     * @param  $prenom4_unite_legale Quatrième prénom déclaré pour une personne physique
     *
     * @return $this
     */
    public function setPrenom4UniteLegale($prenom4_unite_legale)
    {
        $this->container['prenom4_unite_legale'] = $prenom4_unite_legale;

        return $this;
    }

    /**
     * Gets prenom_usuel_unite_legale
     *
     * @return 
     */
    public function getPrenomUsuelUniteLegale()
    {
        return $this->container['prenom_usuel_unite_legale'];
    }

    /**
     * Sets prenom_usuel_unite_legale
     *
     * @param  $prenom_usuel_unite_legale Prénom usuel pour les personne physiques, correspond généralement au Prenom1
     *
     * @return $this
     */
    public function setPrenomUsuelUniteLegale($prenom_usuel_unite_legale)
    {
        $this->container['prenom_usuel_unite_legale'] = $prenom_usuel_unite_legale;

        return $this;
    }

    /**
     * Gets pseudonyme_unite_legale
     *
     * @return 
     */
    public function getPseudonymeUniteLegale()
    {
        return $this->container['pseudonyme_unite_legale'];
    }

    /**
     * Sets pseudonyme_unite_legale
     *
     * @param  $pseudonyme_unite_legale Pseudonyme pour les personnes physiques
     *
     * @return $this
     */
    public function setPseudonymeUniteLegale($pseudonyme_unite_legale)
    {
        $this->container['pseudonyme_unite_legale'] = $pseudonyme_unite_legale;

        return $this;
    }

    /**
     * Gets periodes_unite_legale
     *
     * @return 
     */
    public function getPeriodesUniteLegale()
    {
        return $this->container['periodes_unite_legale'];
    }

    /**
     * Sets periodes_unite_legale
     *
     * @param  $periodes_unite_legale periodes_unite_legale
     *
     * @return $this
     */
    public function setPeriodesUniteLegale($periodes_unite_legale)
    {
        $this->container['periodes_unite_legale'] = $periodes_unite_legale;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
