<?php
/**
 * AdresseComplementaireTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * AdresseComplementaireTest Class Doc Comment
 *
 * @category    Class
 * @description Ensemble des variables d&#x27;adresse complémentaire d&#x27;un établissement
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdresseComplementaireTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdresseComplementaire"
     */
    public function testAdresseComplementaire()
    {
    }

    /**
     * Test attribute "complement_adresse2_etablissement"
     */
    public function testPropertyComplementAdresse2Etablissement()
    {
    }

    /**
     * Test attribute "numero_voie2_etablissement"
     */
    public function testPropertyNumeroVoie2Etablissement()
    {
    }

    /**
     * Test attribute "indice_repetition2_etablissement"
     */
    public function testPropertyIndiceRepetition2Etablissement()
    {
    }

    /**
     * Test attribute "type_voie2_etablissement"
     */
    public function testPropertyTypeVoie2Etablissement()
    {
    }

    /**
     * Test attribute "libelle_voie2_etablissement"
     */
    public function testPropertyLibelleVoie2Etablissement()
    {
    }

    /**
     * Test attribute "code_postal2_etablissement"
     */
    public function testPropertyCodePostal2Etablissement()
    {
    }

    /**
     * Test attribute "libelle_commune2_etablissement"
     */
    public function testPropertyLibelleCommune2Etablissement()
    {
    }

    /**
     * Test attribute "libelle_commune_etranger2_etablissement"
     */
    public function testPropertyLibelleCommuneEtranger2Etablissement()
    {
    }

    /**
     * Test attribute "distribution_speciale2_etablissement"
     */
    public function testPropertyDistributionSpeciale2Etablissement()
    {
    }

    /**
     * Test attribute "code_commune2_etablissement"
     */
    public function testPropertyCodeCommune2Etablissement()
    {
    }

    /**
     * Test attribute "code_cedex2_etablissement"
     */
    public function testPropertyCodeCedex2Etablissement()
    {
    }

    /**
     * Test attribute "libelle_cedex2_etablissement"
     */
    public function testPropertyLibelleCedex2Etablissement()
    {
    }

    /**
     * Test attribute "code_pays_etranger2_etablissement"
     */
    public function testPropertyCodePaysEtranger2Etablissement()
    {
    }

    /**
     * Test attribute "libelle_pays_etranger2_etablissement"
     */
    public function testPropertyLibellePaysEtranger2Etablissement()
    {
    }
}
