<?php
/**
 * LienSuccessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LienSuccessionTest Class Doc Comment
 *
 * @category    Class
 * @description LienSuccession
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LienSuccessionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LienSuccession"
     */
    public function testLienSuccession()
    {
    }

    /**
     * Test attribute "siret_etablissement_predecesseur"
     */
    public function testPropertySiretEtablissementPredecesseur()
    {
    }

    /**
     * Test attribute "siret_etablissement_successeur"
     */
    public function testPropertySiretEtablissementSuccesseur()
    {
    }

    /**
     * Test attribute "date_lien_succession"
     */
    public function testPropertyDateLienSuccession()
    {
    }

    /**
     * Test attribute "transfert_siege"
     */
    public function testPropertyTransfertSiege()
    {
    }

    /**
     * Test attribute "continuite_economique"
     */
    public function testPropertyContinuiteEconomique()
    {
    }

    /**
     * Test attribute "date_dernier_traitement_lien_succession"
     */
    public function testPropertyDateDernierTraitementLienSuccession()
    {
    }
}
