<?php
/**
 * PeriodeUniteLegaleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sirene\Client;

use PHPUnit\Framework\TestCase;

/**
 * PeriodeUniteLegaleTest Class Doc Comment
 *
 * @category    Class
 * @description PeriodeUniteLegale
 * @package     Sirene\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PeriodeUniteLegaleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PeriodeUniteLegale"
     */
    public function testPeriodeUniteLegale()
    {
    }

    /**
     * Test attribute "date_fin"
     */
    public function testPropertyDateFin()
    {
    }

    /**
     * Test attribute "date_debut"
     */
    public function testPropertyDateDebut()
    {
    }

    /**
     * Test attribute "etat_administratif_unite_legale"
     */
    public function testPropertyEtatAdministratifUniteLegale()
    {
    }

    /**
     * Test attribute "changement_etat_administratif_unite_legale"
     */
    public function testPropertyChangementEtatAdministratifUniteLegale()
    {
    }

    /**
     * Test attribute "nom_unite_legale"
     */
    public function testPropertyNomUniteLegale()
    {
    }

    /**
     * Test attribute "changement_nom_unite_legale"
     */
    public function testPropertyChangementNomUniteLegale()
    {
    }

    /**
     * Test attribute "nom_usage_unite_legale"
     */
    public function testPropertyNomUsageUniteLegale()
    {
    }

    /**
     * Test attribute "changement_nom_usage_unite_legale"
     */
    public function testPropertyChangementNomUsageUniteLegale()
    {
    }

    /**
     * Test attribute "denomination_unite_legale"
     */
    public function testPropertyDenominationUniteLegale()
    {
    }

    /**
     * Test attribute "changement_denomination_unite_legale"
     */
    public function testPropertyChangementDenominationUniteLegale()
    {
    }

    /**
     * Test attribute "denomination_usuelle1_unite_legale"
     */
    public function testPropertyDenominationUsuelle1UniteLegale()
    {
    }

    /**
     * Test attribute "denomination_usuelle2_unite_legale"
     */
    public function testPropertyDenominationUsuelle2UniteLegale()
    {
    }

    /**
     * Test attribute "denomination_usuelle3_unite_legale"
     */
    public function testPropertyDenominationUsuelle3UniteLegale()
    {
    }

    /**
     * Test attribute "categorie_juridique_unite_legale"
     */
    public function testPropertyCategorieJuridiqueUniteLegale()
    {
    }

    /**
     * Test attribute "changement_categorie_juridique_unite_legale"
     */
    public function testPropertyChangementCategorieJuridiqueUniteLegale()
    {
    }

    /**
     * Test attribute "activite_principale_unite_legale"
     */
    public function testPropertyActivitePrincipaleUniteLegale()
    {
    }

    /**
     * Test attribute "nomenclature_activite_principale_unite_legale"
     */
    public function testPropertyNomenclatureActivitePrincipaleUniteLegale()
    {
    }

    /**
     * Test attribute "changement_activite_principale_unite_legale"
     */
    public function testPropertyChangementActivitePrincipaleUniteLegale()
    {
    }

    /**
     * Test attribute "nic_siege_unite_legale"
     */
    public function testPropertyNicSiegeUniteLegale()
    {
    }

    /**
     * Test attribute "changement_nic_siege_unite_legale"
     */
    public function testPropertyChangementNicSiegeUniteLegale()
    {
    }

    /**
     * Test attribute "economie_sociale_solidaire_unite_legale"
     */
    public function testPropertyEconomieSocialeSolidaireUniteLegale()
    {
    }

    /**
     * Test attribute "changement_economie_sociale_solidaire_unite_legale"
     */
    public function testPropertyChangementEconomieSocialeSolidaireUniteLegale()
    {
    }

    /**
     * Test attribute "societe_mission_unite_legale"
     */
    public function testPropertySocieteMissionUniteLegale()
    {
    }

    /**
     * Test attribute "changement_societe_mission_unite_legale"
     */
    public function testPropertyChangementSocieteMissionUniteLegale()
    {
    }

    /**
     * Test attribute "caractere_employeur_unite_legale"
     */
    public function testPropertyCaractereEmployeurUniteLegale()
    {
    }

    /**
     * Test attribute "changement_caractere_employeur_unite_legale"
     */
    public function testPropertyChangementCaractereEmployeurUniteLegale()
    {
    }

    /**
     * Test attribute "changement_denomination_usuelle_unite_legale"
     */
    public function testPropertyChangementDenominationUsuelleUniteLegale()
    {
    }
}
