<?php
/**
 * PeriodeEtablissementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PeriodeEtablissementTest Class Doc Comment
 *
 * @category    Class
 * @description Ensemble des variables historisées de l&#x27;établissement entre dateDebut et dateFin
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PeriodeEtablissementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PeriodeEtablissement"
     */
    public function testPeriodeEtablissement()
    {
    }

    /**
     * Test attribute "date_fin"
     */
    public function testPropertyDateFin()
    {
    }

    /**
     * Test attribute "date_debut"
     */
    public function testPropertyDateDebut()
    {
    }

    /**
     * Test attribute "etat_administratif_etablissement"
     */
    public function testPropertyEtatAdministratifEtablissement()
    {
    }

    /**
     * Test attribute "changement_etat_administratif_etablissement"
     */
    public function testPropertyChangementEtatAdministratifEtablissement()
    {
    }

    /**
     * Test attribute "enseigne1_etablissement"
     */
    public function testPropertyEnseigne1Etablissement()
    {
    }

    /**
     * Test attribute "enseigne2_etablissement"
     */
    public function testPropertyEnseigne2Etablissement()
    {
    }

    /**
     * Test attribute "enseigne3_etablissement"
     */
    public function testPropertyEnseigne3Etablissement()
    {
    }

    /**
     * Test attribute "changement_enseigne_etablissement"
     */
    public function testPropertyChangementEnseigneEtablissement()
    {
    }

    /**
     * Test attribute "denomination_usuelle_etablissement"
     */
    public function testPropertyDenominationUsuelleEtablissement()
    {
    }

    /**
     * Test attribute "changement_denomination_usuelle_etablissement"
     */
    public function testPropertyChangementDenominationUsuelleEtablissement()
    {
    }

    /**
     * Test attribute "activite_principale_etablissement"
     */
    public function testPropertyActivitePrincipaleEtablissement()
    {
    }

    /**
     * Test attribute "nomenclature_activite_principale_etablissement"
     */
    public function testPropertyNomenclatureActivitePrincipaleEtablissement()
    {
    }

    /**
     * Test attribute "changement_activite_principale_etablissement"
     */
    public function testPropertyChangementActivitePrincipaleEtablissement()
    {
    }

    /**
     * Test attribute "caractere_employeur_etablissement"
     */
    public function testPropertyCaractereEmployeurEtablissement()
    {
    }

    /**
     * Test attribute "changement_caractere_employeur_etablissement"
     */
    public function testPropertyChangementCaractereEmployeurEtablissement()
    {
    }
}
