<?php
/**
 * UniteLegaleEtablissementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * UniteLegaleEtablissementTest Class Doc Comment
 *
 * @category    Class
 * @description Objet représentant les valeurs courante de l&#x27;unité légale de l&#x27;établissement
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UniteLegaleEtablissementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UniteLegaleEtablissement"
     */
    public function testUniteLegaleEtablissement()
    {
    }

    /**
     * Test attribute "statut_diffusion_unite_legale"
     */
    public function testPropertyStatutDiffusionUniteLegale()
    {
    }

    /**
     * Test attribute "unite_purgee_unite_legale"
     */
    public function testPropertyUnitePurgeeUniteLegale()
    {
    }

    /**
     * Test attribute "date_creation_unite_legale"
     */
    public function testPropertyDateCreationUniteLegale()
    {
    }

    /**
     * Test attribute "date_naissance_unite_legale"
     */
    public function testPropertyDateNaissanceUniteLegale()
    {
    }

    /**
     * Test attribute "code_commune_naissance_unite_legale"
     */
    public function testPropertyCodeCommuneNaissanceUniteLegale()
    {
    }

    /**
     * Test attribute "code_pays_naissance_unite_legale"
     */
    public function testPropertyCodePaysNaissanceUniteLegale()
    {
    }

    /**
     * Test attribute "libelle_nationalite_unite_legale"
     */
    public function testPropertyLibelleNationaliteUniteLegale()
    {
    }

    /**
     * Test attribute "identifiant_association_unite_legale"
     */
    public function testPropertyIdentifiantAssociationUniteLegale()
    {
    }

    /**
     * Test attribute "tranche_effectifs_unite_legale"
     */
    public function testPropertyTrancheEffectifsUniteLegale()
    {
    }

    /**
     * Test attribute "annee_effectifs_unite_legale"
     */
    public function testPropertyAnneeEffectifsUniteLegale()
    {
    }

    /**
     * Test attribute "date_dernier_traitement_unite_legale"
     */
    public function testPropertyDateDernierTraitementUniteLegale()
    {
    }

    /**
     * Test attribute "categorie_entreprise"
     */
    public function testPropertyCategorieEntreprise()
    {
    }

    /**
     * Test attribute "annee_categorie_entreprise"
     */
    public function testPropertyAnneeCategorieEntreprise()
    {
    }

    /**
     * Test attribute "sigle_unite_legale"
     */
    public function testPropertySigleUniteLegale()
    {
    }

    /**
     * Test attribute "sexe_unite_legale"
     */
    public function testPropertySexeUniteLegale()
    {
    }

    /**
     * Test attribute "prenom1_unite_legale"
     */
    public function testPropertyPrenom1UniteLegale()
    {
    }

    /**
     * Test attribute "prenom2_unite_legale"
     */
    public function testPropertyPrenom2UniteLegale()
    {
    }

    /**
     * Test attribute "prenom3_unite_legale"
     */
    public function testPropertyPrenom3UniteLegale()
    {
    }

    /**
     * Test attribute "prenom4_unite_legale"
     */
    public function testPropertyPrenom4UniteLegale()
    {
    }

    /**
     * Test attribute "prenom_usuel_unite_legale"
     */
    public function testPropertyPrenomUsuelUniteLegale()
    {
    }

    /**
     * Test attribute "pseudonyme_unite_legale"
     */
    public function testPropertyPseudonymeUniteLegale()
    {
    }

    /**
     * Test attribute "etat_administratif_unite_legale"
     */
    public function testPropertyEtatAdministratifUniteLegale()
    {
    }

    /**
     * Test attribute "nom_unite_legale"
     */
    public function testPropertyNomUniteLegale()
    {
    }

    /**
     * Test attribute "denomination_unite_legale"
     */
    public function testPropertyDenominationUniteLegale()
    {
    }

    /**
     * Test attribute "denomination_usuelle1_unite_legale"
     */
    public function testPropertyDenominationUsuelle1UniteLegale()
    {
    }

    /**
     * Test attribute "denomination_usuelle2_unite_legale"
     */
    public function testPropertyDenominationUsuelle2UniteLegale()
    {
    }

    /**
     * Test attribute "denomination_usuelle3_unite_legale"
     */
    public function testPropertyDenominationUsuelle3UniteLegale()
    {
    }

    /**
     * Test attribute "activite_principale_unite_legale"
     */
    public function testPropertyActivitePrincipaleUniteLegale()
    {
    }

    /**
     * Test attribute "categorie_juridique_unite_legale"
     */
    public function testPropertyCategorieJuridiqueUniteLegale()
    {
    }

    /**
     * Test attribute "nic_siege_unite_legale"
     */
    public function testPropertyNicSiegeUniteLegale()
    {
    }

    /**
     * Test attribute "nomenclature_activite_principale_unite_legale"
     */
    public function testPropertyNomenclatureActivitePrincipaleUniteLegale()
    {
    }

    /**
     * Test attribute "nom_usage_unite_legale"
     */
    public function testPropertyNomUsageUniteLegale()
    {
    }

    /**
     * Test attribute "economie_sociale_solidaire_unite_legale"
     */
    public function testPropertyEconomieSocialeSolidaireUniteLegale()
    {
    }

    /**
     * Test attribute "societe_mission_unite_legale"
     */
    public function testPropertySocieteMissionUniteLegale()
    {
    }

    /**
     * Test attribute "caractere_employeur_unite_legale"
     */
    public function testPropertyCaractereEmployeurUniteLegale()
    {
    }
}
