<?php
/**
 * UniteLegaleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sirene API
 *
 * Documentation de l'API Sirene
 *
 * OpenAPI spec version: 3.11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.72
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Sirene\Client;

use Sirene\Client\Configuration;
use Sirene\Client\ApiException;
use Sirene\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UniteLegaleApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sirene\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UniteLegaleApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for findByGetUniteLegale
     *
     * Recherche multicritère d'unités légales.
     *
     */
    public function testFindByGetUniteLegale()
    {
    }

    /**
     * Test case for findByPostUniteLegale
     *
     * Recherche multicritère d'unités légales.
     *
     */
    public function testFindByPostUniteLegaleForm()
    {
    }

    /**
     * Test case for findBySiren
     *
     * Recherche d'une unité légale par son numéro Siren.
     *
     */
    public function testFindBySiren()
    {
    }
}
